/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-sqlite'
import {
  sqliteTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  text,
  numeric,
} from '@payloadcms/db-sqlite/drizzle/sqlite-core'
import { sql, relations } from '@payloadcms/db-sqlite/drizzle'

export const orders_timeline = sqliteTable(
  'orders_timeline',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    title: text('title').notNull(),
    date: text('date')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    type: text('type', {
      enum: [
        'note',
        'order_created',
        'order_paid',
        'order_cancelled',
        'refund_issued',
        'fulfillment_started',
        'shipped',
        'delivered',
        'return_requested',
        'return_completed',
        'other',
      ],
    }).notNull(),
    createdBy: integer('created_by_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    details: text('details'),
  },
  (columns) => ({
    _orderIdx: index('orders_timeline_order_idx').on(columns._order),
    _parentIDIdx: index('orders_timeline_parent_id_idx').on(columns._parentID),
    orders_timeline_created_by_idx: index('orders_timeline_created_by_idx').on(columns.createdBy),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [orders.id],
      name: 'orders_timeline_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const orders = sqliteTable(
  'orders',
  {
    id: integer('id').primaryKey(),
    orderId: text('order_id').notNull(),
    totalAmount: numeric('total_amount').notNull(),
    user: integer('user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    source: text('source', { enum: ['manual'] }).default('manual'),
    currency: text('currency').notNull(),
    paymentStatus: text('payment_status', { enum: ['pending', 'paid', 'failed', 'refunded'] })
      .notNull()
      .default('pending'),
    orderStatus: text('order_status', {
      enum: ['pending', 'processing', 'shipped', 'delivered', 'canceled'],
    })
      .notNull()
      .default('pending'),
    payment: integer('payment_id').references(() => payments.id, {
      onDelete: 'set null',
    }),
    shipping: integer('shipping_id').references(() => shipping.id, {
      onDelete: 'set null',
    }),
    paymentIntentId: text('payment_intent_id'),
    sessionId: text('session_id'),
    sessionUrl: text('session_url'),
    paymentMethod: text('payment_method'),
    receiptUrl: text('receipt_url'),
    metadata: text('metadata', { mode: 'json' }),
    shippingAddress: text('shipping_address', { mode: 'json' }),
    billingAddress: text('billing_address', { mode: 'json' }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => ({
    orders_order_id_idx: uniqueIndex('orders_order_id_idx').on(columns.orderId),
    orders_user_idx: index('orders_user_idx').on(columns.user),
    orders_payment_idx: index('orders_payment_idx').on(columns.payment),
    orders_shipping_idx: index('orders_shipping_idx').on(columns.shipping),
    orders_updated_at_idx: index('orders_updated_at_idx').on(columns.updatedAt),
    orders_created_at_idx: index('orders_created_at_idx').on(columns.createdAt),
  }),
)

export const collections = sqliteTable(
  'collections',
  {
    id: integer('id').primaryKey(),
    title: text('title').notNull(),
    description: text('description'),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    featured: integer('featured', { mode: 'boolean' }).default(false),
    visible: integer('visible', { mode: 'boolean' }).default(true),
    handle: text('handle'),
    meta_title: text('meta_title'),
    meta_description: text('meta_description'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => ({
    collections_image_idx: index('collections_image_idx').on(columns.image),
    collections_handle_idx: index('collections_handle_idx').on(columns.handle),
    collections_updated_at_idx: index('collections_updated_at_idx').on(columns.updatedAt),
    collections_created_at_idx: index('collections_created_at_idx').on(columns.createdAt),
  }),
)

export const products_sales_channels = sqliteTable(
  'products_sales_channels',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: text('value', { enum: ['all', 'onlineStore', 'pos', 'mobileApp'] }),
    id: integer('id').primaryKey(),
  },
  (columns) => ({
    orderIdx: index('products_sales_channels_order_idx').on(columns.order),
    parentIdx: index('products_sales_channels_parent_idx').on(columns.parent),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [products.id],
      name: 'products_sales_channels_parent_fk',
    }).onDelete('cascade'),
  }),
)

export const products_variant_options = sqliteTable(
  'products_variant_options',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    option: text('option').notNull(),
  },
  (columns) => ({
    _orderIdx: index('products_variant_options_order_idx').on(columns._order),
    _parentIDIdx: index('products_variant_options_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [products.id],
      name: 'products_variant_options_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const products_variants_options = sqliteTable(
  'products_variants_options',
  {
    _order: integer('_order').notNull(),
    _parentID: text('_parent_id').notNull(),
    id: text('id').primaryKey(),
    option: text('option').notNull(),
    value: text('value').notNull(),
  },
  (columns) => ({
    _orderIdx: index('products_variants_options_order_idx').on(columns._order),
    _parentIDIdx: index('products_variants_options_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [products_variants.id],
      name: 'products_variants_options_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const products_variants = sqliteTable(
  'products_variants',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    vid: text('vid'),
    sku: text('sku'),
    price: numeric('price').notNull(),
    originalPrice: numeric('original_price'),
    stockCount: numeric('stock_count').default('0'),
  },
  (columns) => ({
    _orderIdx: index('products_variants_order_idx').on(columns._order),
    _parentIDIdx: index('products_variants_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [products.id],
      name: 'products_variants_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const products_custom_fields = sqliteTable(
  'products_custom_fields',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    value: text('value'),
  },
  (columns) => ({
    _orderIdx: index('products_custom_fields_order_idx').on(columns._order),
    _parentIDIdx: index('products_custom_fields_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [products.id],
      name: 'products_custom_fields_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const products = sqliteTable(
  'products',
  {
    id: integer('id').primaryKey(),
    pid: text('pid'),
    title: text('title').notNull(),
    currency: text('currency'),
    visible: integer('visible', { mode: 'boolean' }).default(true),
    featured: integer('featured', { mode: 'boolean' }).default(false),
    inStock: integer('in_stock', { mode: 'boolean' }).default(true),
    source: text('source', { enum: ['manual'] }).default('manual'),
    description: text('description'),
    handle: text('handle'),
    meta_title: text('meta_title'),
    meta_description: text('meta_description'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => ({
    products_handle_idx: index('products_handle_idx').on(columns.handle),
    products_updated_at_idx: index('products_updated_at_idx').on(columns.updatedAt),
    products_created_at_idx: index('products_created_at_idx').on(columns.createdAt),
  }),
)

export const products_texts = sqliteTable(
  'products_texts',
  {
    id: integer('id').primaryKey(),
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    text: text('text'),
  },
  (columns) => ({
    orderParentIdx: index('products_texts_order_parent_idx').on(columns.order, columns.parent),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [products.id],
      name: 'products_texts_parent_fk',
    }).onDelete('cascade'),
  }),
)

export const products_rels = sqliteTable(
  'products_rels',
  {
    id: integer('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    collectionsID: integer('collections_id'),
    mediaID: integer('media_id'),
  },
  (columns) => ({
    order: index('products_rels_order_idx').on(columns.order),
    parentIdx: index('products_rels_parent_idx').on(columns.parent),
    pathIdx: index('products_rels_path_idx').on(columns.path),
    products_rels_collections_id_idx: index('products_rels_collections_id_idx').on(
      columns.collectionsID,
    ),
    products_rels_media_id_idx: index('products_rels_media_id_idx').on(columns.mediaID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [products.id],
      name: 'products_rels_parent_fk',
    }).onDelete('cascade'),
    collectionsIdFk: foreignKey({
      columns: [columns['collectionsID']],
      foreignColumns: [collections.id],
      name: 'products_rels_collections_fk',
    }).onDelete('cascade'),
    mediaIdFk: foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'products_rels_media_fk',
    }).onDelete('cascade'),
  }),
)

export const users_roles = sqliteTable(
  'users_roles',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: text('value', { enum: ['admin', 'customer'] }),
    id: integer('id').primaryKey(),
  },
  (columns) => ({
    orderIdx: index('users_roles_order_idx').on(columns.order),
    parentIdx: index('users_roles_parent_idx').on(columns.parent),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [users.id],
      name: 'users_roles_parent_fk',
    }).onDelete('cascade'),
  }),
)

export const users_sessions = sqliteTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    createdAt: text('created_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    expiresAt: text('expires_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => ({
    _orderIdx: index('users_sessions_order_idx').on(columns._order),
    _parentIDIdx: index('users_sessions_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const users = sqliteTable(
  'users',
  {
    id: integer('id').primaryKey(),
    firstName: text('first_name'),
    lastName: text('last_name'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    email: text('email').notNull(),
    resetPasswordToken: text('reset_password_token'),
    resetPasswordExpiration: text('reset_password_expiration').default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    salt: text('salt'),
    hash: text('hash'),
    loginAttempts: numeric('login_attempts').default('0'),
    lockUntil: text('lock_until').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => ({
    users_updated_at_idx: index('users_updated_at_idx').on(columns.updatedAt),
    users_created_at_idx: index('users_created_at_idx').on(columns.createdAt),
    users_email_idx: uniqueIndex('users_email_idx').on(columns.email),
  }),
)

export const media = sqliteTable(
  'media',
  {
    id: integer('id').primaryKey(),
    alt: text('alt').notNull(),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    url: text('url'),
    thumbnailURL: text('thumbnail_u_r_l'),
    filename: text('filename'),
    mimeType: text('mime_type'),
    filesize: numeric('filesize'),
    width: numeric('width'),
    height: numeric('height'),
    focalX: numeric('focal_x'),
    focalY: numeric('focal_y'),
  },
  (columns) => ({
    media_updated_at_idx: index('media_updated_at_idx').on(columns.updatedAt),
    media_created_at_idx: index('media_created_at_idx').on(columns.createdAt),
    media_filename_idx: uniqueIndex('media_filename_idx').on(columns.filename),
  }),
)

export const policies = sqliteTable(
  'policies',
  {
    id: integer('id').primaryKey(),
    title: text('title').notNull(),
    description: text('description'),
    handle: text('handle'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => ({
    policies_handle_idx: index('policies_handle_idx').on(columns.handle),
    policies_updated_at_idx: index('policies_updated_at_idx').on(columns.updatedAt),
    policies_created_at_idx: index('policies_created_at_idx').on(columns.createdAt),
  }),
)

export const gift_cards = sqliteTable(
  'gift_cards',
  {
    id: integer('id').primaryKey(),
    code: text('code').notNull(),
    value: numeric('value').notNull(),
    customer: integer('customer_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    expiryDate: text('expiry_date').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => ({
    gift_cards_customer_idx: index('gift_cards_customer_idx').on(columns.customer),
    gift_cards_updated_at_idx: index('gift_cards_updated_at_idx').on(columns.updatedAt),
    gift_cards_created_at_idx: index('gift_cards_created_at_idx').on(columns.createdAt),
  }),
)

export const pages = sqliteTable(
  'pages',
  {
    id: integer('id').primaryKey(),
    title: text('title').notNull().default('New Page'),
    description: text('description'),
    handle: text('handle').notNull().default('new-page'),
    page: text('page', { mode: 'json' }).notNull(),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => ({
    pages_updated_at_idx: index('pages_updated_at_idx').on(columns.updatedAt),
    pages_created_at_idx: index('pages_created_at_idx').on(columns.createdAt),
  }),
)

export const payments_blocks_manual_details = sqliteTable(
  'payments_blocks_manual_details',
  {
    _order: integer('_order').notNull(),
    _parentID: text('_parent_id').notNull(),
    id: text('id').primaryKey(),
    label: text('label'),
    value: text('value'),
  },
  (columns) => ({
    _orderIdx: index('payments_blocks_manual_details_order_idx').on(columns._order),
    _parentIDIdx: index('payments_blocks_manual_details_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [payments_blocks_manual.id],
      name: 'payments_blocks_manual_details_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const payments_blocks_manual = sqliteTable(
  'payments_blocks_manual',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: text('id').primaryKey(),
    methodType: text('method_type', {
      enum: ['cod', 'bankTransfer', 'inStore', 'other'],
    }).notNull(),
    instructions: text('instructions').notNull(),
    blockName: text('block_name'),
  },
  (columns) => ({
    _orderIdx: index('payments_blocks_manual_order_idx').on(columns._order),
    _parentIDIdx: index('payments_blocks_manual_parent_id_idx').on(columns._parentID),
    _pathIdx: index('payments_blocks_manual_path_idx').on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [payments.id],
      name: 'payments_blocks_manual_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const payments_blocks_stripe = sqliteTable(
  'payments_blocks_stripe',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: text('id').primaryKey(),
    providerName: text('provider_name').notNull().default('Stripe'),
    testMode: integer('test_mode', { mode: 'boolean' }),
    methodType: text('method_type', { enum: ['card', 'ach', 'auto'] }).default('auto'),
    stripeSecretKey: text('stripe_secret_key').notNull(),
    stripeWebhooksEndpointSecret: text('stripe_webhooks_endpoint_secret').notNull(),
    publishableKey: text('publishable_key').notNull(),
    blockName: text('block_name'),
  },
  (columns) => ({
    _orderIdx: index('payments_blocks_stripe_order_idx').on(columns._order),
    _parentIDIdx: index('payments_blocks_stripe_parent_id_idx').on(columns._parentID),
    _pathIdx: index('payments_blocks_stripe_path_idx').on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [payments.id],
      name: 'payments_blocks_stripe_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const payments = sqliteTable(
  'payments',
  {
    id: integer('id').primaryKey(),
    name: text('name').notNull(),
    enabled: integer('enabled', { mode: 'boolean' }).default(true),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => ({
    payments_updated_at_idx: index('payments_updated_at_idx').on(columns.updatedAt),
    payments_created_at_idx: index('payments_created_at_idx').on(columns.createdAt),
  }),
)

export const locations = sqliteTable(
  'locations',
  {
    id: integer('id').primaryKey(),
    name: text('name').notNull(),
    address: text('address').notNull(),
    coordinates: text('coordinates', { mode: 'json' }),
    contactPhone: text('contact_phone'),
    hours: text('hours'),
    enabled: integer('enabled', { mode: 'boolean' }).default(true),
    isPickupLocation: integer('is_pickup_location', { mode: 'boolean' }).default(false),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => ({
    locations_updated_at_idx: index('locations_updated_at_idx').on(columns.updatedAt),
    locations_created_at_idx: index('locations_created_at_idx').on(columns.createdAt),
  }),
)

export const shipping_blocks_custom_shipping = sqliteTable(
  'shipping_blocks_custom_shipping',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: text('id').primaryKey(),
    baseRate: numeric('base_rate').notNull(),
    freeShippingMinOrder: numeric('free_shipping_min_order'),
    estimatedDeliveryDays: text('estimated_delivery_days'),
    notes: text('notes'),
    blockName: text('block_name'),
  },
  (columns) => ({
    _orderIdx: index('shipping_blocks_custom_shipping_order_idx').on(columns._order),
    _parentIDIdx: index('shipping_blocks_custom_shipping_parent_id_idx').on(columns._parentID),
    _pathIdx: index('shipping_blocks_custom_shipping_path_idx').on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [shipping.id],
      name: 'shipping_blocks_custom_shipping_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const shipping = sqliteTable(
  'shipping',
  {
    id: integer('id').primaryKey(),
    name: text('name').notNull(),
    enabled: integer('enabled', { mode: 'boolean' }).default(true),
    location: integer('location_id').references(() => locations.id, {
      onDelete: 'set null',
    }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => ({
    shipping_location_idx: index('shipping_location_idx').on(columns.location),
    shipping_updated_at_idx: index('shipping_updated_at_idx').on(columns.updatedAt),
    shipping_created_at_idx: index('shipping_created_at_idx').on(columns.createdAt),
  }),
)

export const payload_locked_documents = sqliteTable(
  'payload_locked_documents',
  {
    id: integer('id').primaryKey(),
    globalSlug: text('global_slug'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => ({
    payload_locked_documents_global_slug_idx: index('payload_locked_documents_global_slug_idx').on(
      columns.globalSlug,
    ),
    payload_locked_documents_updated_at_idx: index('payload_locked_documents_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_locked_documents_created_at_idx: index('payload_locked_documents_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const payload_locked_documents_rels = sqliteTable(
  'payload_locked_documents_rels',
  {
    id: integer('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    ordersID: integer('orders_id'),
    collectionsID: integer('collections_id'),
    productsID: integer('products_id'),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    policiesID: integer('policies_id'),
    'gift-cardsID': integer('gift_cards_id'),
    pagesID: integer('pages_id'),
    paymentsID: integer('payments_id'),
    locationsID: integer('locations_id'),
    shippingID: integer('shipping_id'),
  },
  (columns) => ({
    order: index('payload_locked_documents_rels_order_idx').on(columns.order),
    parentIdx: index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_locked_documents_rels_path_idx').on(columns.path),
    payload_locked_documents_rels_orders_id_idx: index(
      'payload_locked_documents_rels_orders_id_idx',
    ).on(columns.ordersID),
    payload_locked_documents_rels_collections_id_idx: index(
      'payload_locked_documents_rels_collections_id_idx',
    ).on(columns.collectionsID),
    payload_locked_documents_rels_products_id_idx: index(
      'payload_locked_documents_rels_products_id_idx',
    ).on(columns.productsID),
    payload_locked_documents_rels_users_id_idx: index(
      'payload_locked_documents_rels_users_id_idx',
    ).on(columns.usersID),
    payload_locked_documents_rels_media_id_idx: index(
      'payload_locked_documents_rels_media_id_idx',
    ).on(columns.mediaID),
    payload_locked_documents_rels_policies_id_idx: index(
      'payload_locked_documents_rels_policies_id_idx',
    ).on(columns.policiesID),
    payload_locked_documents_rels_gift_cards_id_idx: index(
      'payload_locked_documents_rels_gift_cards_id_idx',
    ).on(columns['gift-cardsID']),
    payload_locked_documents_rels_pages_id_idx: index(
      'payload_locked_documents_rels_pages_id_idx',
    ).on(columns.pagesID),
    payload_locked_documents_rels_payments_id_idx: index(
      'payload_locked_documents_rels_payments_id_idx',
    ).on(columns.paymentsID),
    payload_locked_documents_rels_locations_id_idx: index(
      'payload_locked_documents_rels_locations_id_idx',
    ).on(columns.locationsID),
    payload_locked_documents_rels_shipping_id_idx: index(
      'payload_locked_documents_rels_shipping_id_idx',
    ).on(columns.shippingID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    ordersIdFk: foreignKey({
      columns: [columns['ordersID']],
      foreignColumns: [orders.id],
      name: 'payload_locked_documents_rels_orders_fk',
    }).onDelete('cascade'),
    collectionsIdFk: foreignKey({
      columns: [columns['collectionsID']],
      foreignColumns: [collections.id],
      name: 'payload_locked_documents_rels_collections_fk',
    }).onDelete('cascade'),
    productsIdFk: foreignKey({
      columns: [columns['productsID']],
      foreignColumns: [products.id],
      name: 'payload_locked_documents_rels_products_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    mediaIdFk: foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    policiesIdFk: foreignKey({
      columns: [columns['policiesID']],
      foreignColumns: [policies.id],
      name: 'payload_locked_documents_rels_policies_fk',
    }).onDelete('cascade'),
    'gift-cardsIdFk': foreignKey({
      columns: [columns['gift-cardsID']],
      foreignColumns: [gift_cards.id],
      name: 'payload_locked_documents_rels_gift_cards_fk',
    }).onDelete('cascade'),
    pagesIdFk: foreignKey({
      columns: [columns['pagesID']],
      foreignColumns: [pages.id],
      name: 'payload_locked_documents_rels_pages_fk',
    }).onDelete('cascade'),
    paymentsIdFk: foreignKey({
      columns: [columns['paymentsID']],
      foreignColumns: [payments.id],
      name: 'payload_locked_documents_rels_payments_fk',
    }).onDelete('cascade'),
    locationsIdFk: foreignKey({
      columns: [columns['locationsID']],
      foreignColumns: [locations.id],
      name: 'payload_locked_documents_rels_locations_fk',
    }).onDelete('cascade'),
    shippingIdFk: foreignKey({
      columns: [columns['shippingID']],
      foreignColumns: [shipping.id],
      name: 'payload_locked_documents_rels_shipping_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_preferences = sqliteTable(
  'payload_preferences',
  {
    id: integer('id').primaryKey(),
    key: text('key'),
    value: text('value', { mode: 'json' }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => ({
    payload_preferences_key_idx: index('payload_preferences_key_idx').on(columns.key),
    payload_preferences_updated_at_idx: index('payload_preferences_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_preferences_created_at_idx: index('payload_preferences_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const payload_preferences_rels = sqliteTable(
  'payload_preferences_rels',
  {
    id: integer('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => ({
    order: index('payload_preferences_rels_order_idx').on(columns.order),
    parentIdx: index('payload_preferences_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_preferences_rels_path_idx').on(columns.path),
    payload_preferences_rels_users_id_idx: index('payload_preferences_rels_users_id_idx').on(
      columns.usersID,
    ),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_migrations = sqliteTable(
  'payload_migrations',
  {
    id: integer('id').primaryKey(),
    name: text('name'),
    batch: numeric('batch'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => ({
    payload_migrations_updated_at_idx: index('payload_migrations_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_migrations_created_at_idx: index('payload_migrations_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const relations_orders_timeline = relations(orders_timeline, ({ one }) => ({
  _parentID: one(orders, {
    fields: [orders_timeline._parentID],
    references: [orders.id],
    relationName: 'timeline',
  }),
  createdBy: one(users, {
    fields: [orders_timeline.createdBy],
    references: [users.id],
    relationName: 'createdBy',
  }),
}))
export const relations_orders = relations(orders, ({ one, many }) => ({
  user: one(users, {
    fields: [orders.user],
    references: [users.id],
    relationName: 'user',
  }),
  payment: one(payments, {
    fields: [orders.payment],
    references: [payments.id],
    relationName: 'payment',
  }),
  shipping: one(shipping, {
    fields: [orders.shipping],
    references: [shipping.id],
    relationName: 'shipping',
  }),
  timeline: many(orders_timeline, {
    relationName: 'timeline',
  }),
}))
export const relations_collections = relations(collections, ({ one }) => ({
  image: one(media, {
    fields: [collections.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_products_sales_channels = relations(products_sales_channels, ({ one }) => ({
  parent: one(products, {
    fields: [products_sales_channels.parent],
    references: [products.id],
    relationName: 'salesChannels',
  }),
}))
export const relations_products_variant_options = relations(
  products_variant_options,
  ({ one }) => ({
    _parentID: one(products, {
      fields: [products_variant_options._parentID],
      references: [products.id],
      relationName: 'variantOptions',
    }),
  }),
)
export const relations_products_variants_options = relations(
  products_variants_options,
  ({ one }) => ({
    _parentID: one(products_variants, {
      fields: [products_variants_options._parentID],
      references: [products_variants.id],
      relationName: 'options',
    }),
  }),
)
export const relations_products_variants = relations(products_variants, ({ one, many }) => ({
  _parentID: one(products, {
    fields: [products_variants._parentID],
    references: [products.id],
    relationName: 'variants',
  }),
  options: many(products_variants_options, {
    relationName: 'options',
  }),
}))
export const relations_products_custom_fields = relations(products_custom_fields, ({ one }) => ({
  _parentID: one(products, {
    fields: [products_custom_fields._parentID],
    references: [products.id],
    relationName: 'customFields',
  }),
}))
export const relations_products_texts = relations(products_texts, ({ one }) => ({
  parent: one(products, {
    fields: [products_texts.parent],
    references: [products.id],
    relationName: '_texts',
  }),
}))
export const relations_products_rels = relations(products_rels, ({ one }) => ({
  parent: one(products, {
    fields: [products_rels.parent],
    references: [products.id],
    relationName: '_rels',
  }),
  collectionsID: one(collections, {
    fields: [products_rels.collectionsID],
    references: [collections.id],
    relationName: 'collections',
  }),
  mediaID: one(media, {
    fields: [products_rels.mediaID],
    references: [media.id],
    relationName: 'media',
  }),
}))
export const relations_products = relations(products, ({ many }) => ({
  salesChannels: many(products_sales_channels, {
    relationName: 'salesChannels',
  }),
  variantOptions: many(products_variant_options, {
    relationName: 'variantOptions',
  }),
  variants: many(products_variants, {
    relationName: 'variants',
  }),
  customFields: many(products_custom_fields, {
    relationName: 'customFields',
  }),
  _texts: many(products_texts, {
    relationName: '_texts',
  }),
  _rels: many(products_rels, {
    relationName: '_rels',
  }),
}))
export const relations_users_roles = relations(users_roles, ({ one }) => ({
  parent: one(users, {
    fields: [users_roles.parent],
    references: [users.id],
    relationName: 'roles',
  }),
}))
export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  roles: many(users_roles, {
    relationName: 'roles',
  }),
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_policies = relations(policies, () => ({}))
export const relations_gift_cards = relations(gift_cards, ({ one }) => ({
  customer: one(users, {
    fields: [gift_cards.customer],
    references: [users.id],
    relationName: 'customer',
  }),
}))
export const relations_pages = relations(pages, () => ({}))
export const relations_payments_blocks_manual_details = relations(
  payments_blocks_manual_details,
  ({ one }) => ({
    _parentID: one(payments_blocks_manual, {
      fields: [payments_blocks_manual_details._parentID],
      references: [payments_blocks_manual.id],
      relationName: 'details',
    }),
  }),
)
export const relations_payments_blocks_manual = relations(
  payments_blocks_manual,
  ({ one, many }) => ({
    _parentID: one(payments, {
      fields: [payments_blocks_manual._parentID],
      references: [payments.id],
      relationName: '_blocks_manual',
    }),
    details: many(payments_blocks_manual_details, {
      relationName: 'details',
    }),
  }),
)
export const relations_payments_blocks_stripe = relations(payments_blocks_stripe, ({ one }) => ({
  _parentID: one(payments, {
    fields: [payments_blocks_stripe._parentID],
    references: [payments.id],
    relationName: '_blocks_stripe',
  }),
}))
export const relations_payments = relations(payments, ({ many }) => ({
  _blocks_manual: many(payments_blocks_manual, {
    relationName: '_blocks_manual',
  }),
  _blocks_stripe: many(payments_blocks_stripe, {
    relationName: '_blocks_stripe',
  }),
}))
export const relations_locations = relations(locations, () => ({}))
export const relations_shipping_blocks_custom_shipping = relations(
  shipping_blocks_custom_shipping,
  ({ one }) => ({
    _parentID: one(shipping, {
      fields: [shipping_blocks_custom_shipping._parentID],
      references: [shipping.id],
      relationName: '_blocks_custom-shipping',
    }),
  }),
)
export const relations_shipping = relations(shipping, ({ one, many }) => ({
  location: one(locations, {
    fields: [shipping.location],
    references: [locations.id],
    relationName: 'location',
  }),
  '_blocks_custom-shipping': many(shipping_blocks_custom_shipping, {
    relationName: '_blocks_custom-shipping',
  }),
}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    ordersID: one(orders, {
      fields: [payload_locked_documents_rels.ordersID],
      references: [orders.id],
      relationName: 'orders',
    }),
    collectionsID: one(collections, {
      fields: [payload_locked_documents_rels.collectionsID],
      references: [collections.id],
      relationName: 'collections',
    }),
    productsID: one(products, {
      fields: [payload_locked_documents_rels.productsID],
      references: [products.id],
      relationName: 'products',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    policiesID: one(policies, {
      fields: [payload_locked_documents_rels.policiesID],
      references: [policies.id],
      relationName: 'policies',
    }),
    'gift-cardsID': one(gift_cards, {
      fields: [payload_locked_documents_rels['gift-cardsID']],
      references: [gift_cards.id],
      relationName: 'gift-cards',
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: 'pages',
    }),
    paymentsID: one(payments, {
      fields: [payload_locked_documents_rels.paymentsID],
      references: [payments.id],
      relationName: 'payments',
    }),
    locationsID: one(locations, {
      fields: [payload_locked_documents_rels.locationsID],
      references: [locations.id],
      relationName: 'locations',
    }),
    shippingID: one(shipping, {
      fields: [payload_locked_documents_rels.shippingID],
      references: [shipping.id],
      relationName: 'shipping',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  orders_timeline: typeof orders_timeline
  orders: typeof orders
  collections: typeof collections
  products_sales_channels: typeof products_sales_channels
  products_variant_options: typeof products_variant_options
  products_variants_options: typeof products_variants_options
  products_variants: typeof products_variants
  products_custom_fields: typeof products_custom_fields
  products: typeof products
  products_texts: typeof products_texts
  products_rels: typeof products_rels
  users_roles: typeof users_roles
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  policies: typeof policies
  gift_cards: typeof gift_cards
  pages: typeof pages
  payments_blocks_manual_details: typeof payments_blocks_manual_details
  payments_blocks_manual: typeof payments_blocks_manual
  payments_blocks_stripe: typeof payments_blocks_stripe
  payments: typeof payments
  locations: typeof locations
  shipping_blocks_custom_shipping: typeof shipping_blocks_custom_shipping
  shipping: typeof shipping
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_orders_timeline: typeof relations_orders_timeline
  relations_orders: typeof relations_orders
  relations_collections: typeof relations_collections
  relations_products_sales_channels: typeof relations_products_sales_channels
  relations_products_variant_options: typeof relations_products_variant_options
  relations_products_variants_options: typeof relations_products_variants_options
  relations_products_variants: typeof relations_products_variants
  relations_products_custom_fields: typeof relations_products_custom_fields
  relations_products_texts: typeof relations_products_texts
  relations_products_rels: typeof relations_products_rels
  relations_products: typeof relations_products
  relations_users_roles: typeof relations_users_roles
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_policies: typeof relations_policies
  relations_gift_cards: typeof relations_gift_cards
  relations_pages: typeof relations_pages
  relations_payments_blocks_manual_details: typeof relations_payments_blocks_manual_details
  relations_payments_blocks_manual: typeof relations_payments_blocks_manual
  relations_payments_blocks_stripe: typeof relations_payments_blocks_stripe
  relations_payments: typeof relations_payments
  relations_locations: typeof relations_locations
  relations_shipping_blocks_custom_shipping: typeof relations_shipping_blocks_custom_shipping
  relations_shipping: typeof relations_shipping
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-sqlite' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
